# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Add_Op.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(395, 220)
        self.opname = QtWidgets.QLineEdit(Form)
        self.opname.setGeometry(QtCore.QRect(10, 100, 351, 22))
        self.opname.setObjectName("opname")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 60, 301, 16))
        self.label.setObjectName("label")
        self.Submit = QtWidgets.QPushButton(Form)
        self.Submit.setGeometry(QtCore.QRect(260, 140, 93, 28))
        self.Submit.setObjectName("Submit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Please enter the name of the new operation."))
        self.Submit.setText(_translate("Form", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
