# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Exit_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(365, 164)
        self.Yesbtn = QtWidgets.QPushButton(Dialog)
        self.Yesbtn.setGeometry(QtCore.QRect(160, 120, 93, 28))
        self.Yesbtn.setObjectName("Yesbtn")
        self.Nobtn = QtWidgets.QPushButton(Dialog)
        self.Nobtn.setGeometry(QtCore.QRect(260, 120, 93, 28))
        self.Nobtn.setObjectName("Nobtn")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(50, 50, 261, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Yesbtn.setText(_translate("Dialog", "Yes"))
        self.Nobtn.setText(_translate("Dialog", "No"))
        self.label.setText(_translate("Dialog", "Exit the system?"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
