# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Login_Gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LgIn(object):
    def setupUi(self, LgIn):
        LgIn.setObjectName("LgIn")
        LgIn.resize(905, 632)
        self.centralwidget = QtWidgets.QWidget(LgIn)
        self.centralwidget.setObjectName("centralwidget")
        self.Id = QtWidgets.QLineEdit(self.centralwidget)
        self.Id.setGeometry(QtCore.QRect(560, 200, 261, 41))
        self.Id.setAutoFillBackground(False)
        self.Id.setStyleSheet("border: 2px solid rgb(240, 105, 37) ;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 54, 80);")
        self.Id.setObjectName("Id")
        self.IDlabel = QtWidgets.QLabel(self.centralwidget)
        self.IDlabel.setGeometry(QtCore.QRect(560, 250, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.IDlabel.setFont(font)
        self.IDlabel.setObjectName("IDlabel")
        self.Passlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.Passlabel_2.setGeometry(QtCore.QRect(560, 330, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.Passlabel_2.setFont(font)
        self.Passlabel_2.setObjectName("Passlabel_2")
        self.passbox = QtWidgets.QLineEdit(self.centralwidget)
        self.passbox.setGeometry(QtCore.QRect(560, 280, 261, 41))
        self.passbox.setStyleSheet("border: 2px solid rgb(240, 105, 37) ;\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 54, 80);")
        self.passbox.setObjectName("passbox")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(-16, 0, 991, 651))
        self.label.setStyleSheet("background-color: rgb(0, 54, 80)")
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(380, 140, 41, 251))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-130, 40, 641, 401))
        self.label_2.setStyleSheet("background-image: url(:/login/TpA.png);")
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/login/TpA.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 220, 371, 101))
        self.label_3.setStyleSheet("background-image: url(:/login/2515772-middle1.png);")
        self.label_3.setText("")
        self.label_3.setPixmap(QtGui.QPixmap(":/login/2515772-middle1.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(600, 370, 171, 41))
        self.pushButton.setStyleSheet("background-color: rgb(240, 105, 37);\n"
"color: rgb(255, 255, 255)")
        self.pushButton.setObjectName("pushButton")
        self.ErrorMsg = QtWidgets.QLabel(self.centralwidget)
        self.ErrorMsg.setGeometry(QtCore.QRect(560, 180, 151, 16))
        self.ErrorMsg.setObjectName("ErrorMsg")
        self.label.raise_()
        self.Id.raise_()
        self.IDlabel.raise_()
        self.Passlabel_2.raise_()
        self.passbox.raise_()
        self.line.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.pushButton.raise_()
        self.ErrorMsg.raise_()
        LgIn.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(LgIn)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 905, 26))
        self.menubar.setObjectName("menubar")
        LgIn.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(LgIn)
        self.statusbar.setObjectName("statusbar")
        LgIn.setStatusBar(self.statusbar)

        self.retranslateUi(LgIn)
        QtCore.QMetaObject.connectSlotsByName(LgIn)

    def retranslateUi(self, LgIn):
        _translate = QtCore.QCoreApplication.translate
        LgIn.setWindowTitle(_translate("LgIn", "MainWindow"))
        self.Id.setWhatsThis(_translate("LgIn", "<html><head/><body><p>ID Number</p></body></html>"))
        self.IDlabel.setText(_translate("LgIn", "<html><head/><body><p><span style=\" color:#ffffff;\">ID Number</span></p></body></html>"))
        self.Passlabel_2.setWhatsThis(_translate("LgIn", "<html><head/><body>color: white;<p><br/></p></body></html>"))
        self.Passlabel_2.setText(_translate("LgIn", "<html><head/><body><p><span style=\" color:#ffffff;\">Password</span></p></body></html>"))
        self.pushButton.setText(_translate("LgIn", "Login"))
        self.ErrorMsg.setText(_translate("LgIn", "<html><head/><body><p><br/></p></body></html>"))
import Login gui_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LgIn = QtWidgets.QMainWindow()
    ui = Ui_LgIn()
    ui.setupUi(LgIn)
    LgIn.show()
    sys.exit(app.exec_())
