# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaintainTime_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 244)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 60, 391, 41))
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.ftimeinput = QtWidgets.QLineEdit(Form)
        self.ftimeinput.setGeometry(QtCore.QRect(10, 120, 371, 22))
        self.ftimeinput.setObjectName("ftimeinput")
        self.Submit = QtWidgets.QPushButton(Form)
        self.Submit.setGeometry(QtCore.QRect(290, 160, 93, 28))
        self.Submit.setObjectName("Submit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Please enter the flight time in hours"))
        self.Submit.setText(_translate("Form", "Submit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
